version: "3.0"
services:
  db:
    image: postgres
    restart: always
    container_name: "db"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: hackme
      POSTGRES_HOST: db
      POSTGRES_DB: pg

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: ..
      dockerfile: docker/app.dockerfile
    container_name: "api"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: api
      POSTGRES_PWD: hackme
      POSTGRES_HOST: db
      POSTGRES_DB: pg
      POSTGRES_PORT: 5432
      TEST_PG_URL: "postgresql://api:hackme@db:5432/api"
