name: Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r tests/requirements.txt
      - name: Install my package
        run: pip install src/
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: messenger
          postgresql user: username
          postgresql password: hackme
      - name: Test with pytest
        run: pytest